agencies/urls.py
# agencies/urls.py
from django.urls import path, include
from .views import confirm_email_and_setup_password
from . import views

app_name = 'agencies'

urlpatterns = [
    path('register/', views.AgencyRegistrationView.as_view(), name='agency_register'),
    path('registration-success/', views.registration_success, name='registration_success'),
    path('login/', views.CustomLoginView.as_view(), name='account_login'), 
    path('logout/', views.CustomLogoutView.as_view(), name='account_logout'),
    path('profile/', views.profile_view, name='profile'), 
    path('agency/profile/', views.agency_profile, name='agency_profile'),
    path('password/reset/', views.CustomPasswordResetView.as_view(), name='account_reset_password'),
    path('password/reset/done/', views.CustomPasswordResetDoneView.as_view(), name='account_reset_password_done'),
    path('password/reset/key/<uidb36>/<key>/', views.CustomPasswordResetFromKeyView.as_view(),name='account_reset_password_from_key'),
    path('password/reset/key/done/', views.CustomPasswordResetFromKeyDoneView.as_view(), name='account_reset_password_from_key_done'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('add_user/', views.add_user, name='add_user'),
    path('accounts/confirm-email/<uidb64>/<token>/', confirm_email_and_setup_password, name='confirm_email_and_setup_password'),
    path('edit_user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('resend-verification/', views.resend_verification_email, name='resend_verification'),
]

crm/urls.py
# crm/urls.py

from django.urls import path
from . import views

app_name = 'crm'

urlpatterns = [
    path('', views.crm_index, name='index'),
    path('add_company/', views.add_company, name='add_company'),  
    path('company/<int:pk>/edit/', views.edit_company, name='edit_company'),
    path('company/<int:pk>/delete/', views.delete_company, name='delete_company'),
    path('company/<int:pk>/add-contact/', views.add_contact, name='add_contact'), 
    path('company/<int:pk>/add-notes/', views.add_company_notes, name='add_company_notes'),
    path('company/<int:pk>/edit-notes/', views.edit_company_notes, name='edit_company_notes'),
    path('company/<int:pk>/delete-notes/', views.delete_company_notes, name='delete_company_notes'),
    path('fetch-company-data/', views.fetch_company_data, name='fetch_company_data'),
    path('search-companies/', views.search_companies, name='search_companies'),
    path('company/<int:pk>/add-transaction-fee/', views.add_transaction_fee, name='add_transaction_fee'),
    path('company/<int:pk>/', views.company_detail, name='company_detail'),
    path('company/<int:pk>/<str:active_tab>/', views.company_detail, name='company_detail_with_tab'),
    path('contact/<int:pk>/', views.contact_detail, name='contact_detail'),
    path('contact/<int:pk>/edit/', views.edit_contact, name='edit_contact'),
    path('contact/<int:pk>/delete/', views.delete_contact_view, name='delete_contact_view'),
    path('contact/<int:pk>/delete/confirm/', views.confirm_delete_contact, name='confirm_delete_contact'),
    path('transaction-fee/<int:pk>/edit/', views.edit_transaction_fee, name='edit_transaction_fee'),
    path('transaction-fee/<int:pk>/delete/', views.delete_transaction_fee, name='delete_transaction_fee'),
]

travault_crm/urls.py
# travault_crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('agencies/', include(('agencies.urls', 'agencies'), namespace='agencies')), 
    path('accounts/', include('allauth.urls')),  # Allauth URLs included
    path('billing/', include('billing.urls')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('agent_support/', include(('agent_support.urls', 'agent_support'), namespace='agent_support')),  
    path('crm/', include(('crm.urls', 'crm'), namespace='crm')),
    path('activity/', include('activity_log.urls', namespace='activity_log')),
    path('tickets/', include('tickets.urls', namespace='tickets')),  # Include the tickets app
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agencies/models.py
# agencies/models.py

from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """
    Custom user model that extends Django's AbstractUser.

    Attributes:
        user_type (str): The type of user, selected from USER_TYPE_CHOICES. Defaults to 'admin'.
        agency (ForeignKey): A foreign key linking the user to an Agency. Can be null or blank.
        first_name (str): The first name of the user. Allows blank values.
        last_name (str): The last name of the user. Allows blank values.
    """

    USER_TYPE_CHOICES = (
        ('admin', 'Admin'),
        ('agent', 'Agent'),
        ('manager', 'Manager'),
        ('sales', 'Sales'),
    )

    # Defines the type of user, which determines their permissions and role in the system
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, default='admin')

    # Links the user to an Agency; allows multiple users to be associated with a single agency
    agency = models.ForeignKey('Agency', on_delete=models.CASCADE, related_name='users', null=True, blank=True)

    first_name = models.CharField(max_length=30, blank=True) 
    last_name = models.CharField(max_length=150, blank=True)  

    def get_full_name(self):
        """Return the first and last name, with a space in between."""
        full_name = f"{self.first_name} {self.last_name}".strip()
        return full_name if full_name else self.username

    def __str__(self):
        return self.get_full_name()


class Agency(models.Model):
    """
    Model representing an agency.

    Attributes:
        agency_name (str): The name of the agency.
        address (str): The full address of the agency.
        phone (str): The contact phone number of the agency.
        email (str): The contact email address of the agency.
        website (URL): The website URL of the agency, optional.
        vat_number (str): The VAT number of the agency, must be unique.
        company_reg_number (str): The company registration number, must be unique.
        employees (str): The size of the agency in terms of employees, chosen from EMPLOYEE_CHOICES.
        business_focus (str): The main business focus of the agency, chosen from BUSINESS_FOCUS_CHOICES.
        contact_name (str): The primary contact person's name for the agency.
        created_at (DateTime): Timestamp when the agency record was created.
        updated_at (DateTime): Timestamp when the agency record was last updated.
    """

    # Choices for the number of employees in the agency
    EMPLOYEE_CHOICES = [
        ('1-10', '1-10'),
        ('11-50', '11-50'),
        ('51-100', '51-100'),
        ('100+', '100+'),
    ]

    # Choices for the business focus of the agency
    BUSINESS_FOCUS_CHOICES = [
        ('corporate', 'Corporate Travel'),
        ('leisure', 'Leisure Travel'),
        ('mixed', 'Mixed'),
    ]

    agency_name = models.CharField("Agency Name", max_length=255)
    address = models.CharField("Business Address", max_length=255)
    phone = models.CharField("Phone Number", max_length=20)
    email = models.EmailField("Email Address")
    website = models.URLField("Website", blank=True, null=True)
    vat_number = models.CharField("VAT Number", max_length=9, unique=True)
    company_reg_number = models.CharField("Company Registration Number", max_length=8, unique=True)
    employees = models.CharField("Number of Employees", max_length=10, choices=EMPLOYEE_CHOICES)
    business_focus = models.CharField("Business Focus", max_length=20, choices=BUSINESS_FOCUS_CHOICES)
    contact_name = models.CharField("Primary Contact Name", max_length=100)
    created_at = models.DateTimeField("Created At", auto_now_add=True)
    updated_at = models.DateTimeField("Updated At", auto_now=True)

    @staticmethod
    def get_default_agency():
        """Returns the first agency in the database."""
        return Agency.objects.first()

    def __str__(self):
        """
        String representation of the Agency object.

        Returns:
            str: The name of the agency.
        """
        return self.agency_name

agencies/templates/users/add_user.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}
<!-- Ensure you load your custom filters if needed -->
{% block head_title %}Add New User - TraVault{% endblock %}

{% block content %}
<section id="add-user" class="bg-gray-200 full-height-bg">
    <!-- Main container for the add user form -->
    <div class="container top-padding roboto">
        <div class="row justify-content-center py-5">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Add New User</h2>

                        <!-- Display form errors if any -->
                        {% if user_form.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for field in user_form %}
                                {% for error in field.errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}

                        <!-- Form to add a new user -->
                        <form method="post">
                            {% csrf_token %}
                            {% for field in user_form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }} <!-- Add class to form fields -->
                                {% if field.help_text %}
                                <div class="form-text text-muted">{{ field.help_text }}</div>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-get-started btn-lg">Add User</button>
                            </div>
                        </form>
                        <div class="mt-3 text-center">
                            <a href="{% url 'agencies:manage_users' %}" class="btn btn-secondary">Back to User
                                Management</a>
                            <!-- Link to navigate back to user management -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

agencies/templates/users/delete_user.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}

{% block head_title %}Delete User - TraVault{% endblock %}

{% block content %}
<section id="delete-user" class="bg-gray-200 full-height-bg">
    <!-- Main container for the delete user confirmation -->
    <div class="container top-padding roboto">
        <div class="row justify-content-center py-5">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Delete User: {{ delete_user.username }}</h2>
                        <!-- Display the username of the user to be deleted -->

                        <p class="text-center text-danger mb-4">Are you sure you want to delete this user? This action
                            cannot be undone.</p>
                        <!-- Warning message about the irreversibility of the action -->

                        <!-- Form to confirm user deletion -->
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="confirmation_name" class="form-label">Type the username to confirm:</label>
                                <input type="text" name="confirmation_name" id="confirmation_name" class="form-control"
                                    placeholder="Enter username to confirm" required>
                                <!-- Input field for username confirmation -->
                            </div>

                            <div class="text-center">
                                <button type="submit" class="btn btn-danger btn-lg">Delete User</button>
                                <!-- Button to submit the form and delete the user -->
                                <a href="{% url 'agencies:manage_users' %}" class="btn btn-secondary btn-lg">Cancel</a>
                                <!-- Button to cancel and return to user management -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

agencies/templates/users/edit_user.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}

{% block head_title %}Edit User - TraVault{% endblock %}

{% block content %}
<section id="edit-user" class="bg-gray-200 full-height-bg">
    <!-- Main container for the edit user form -->
    <div class="container top-padding roboto">
        <div class="row justify-content-center py-5">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Edit User: {{ edit_user.username }}</h2>
                        <!-- Display the username of the user being edited -->

                        <!-- Display form errors if any -->
                        {% if user_form.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for field in user_form %}
                                {% for error in field.errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}

                        <!-- Form to edit user details -->
                        <form method="post">
                            {% csrf_token %}
                            {% for field in user_form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }} <!-- Add class to form fields for styling -->
                                {% if field.help_text %}
                                <div class="form-text text-muted">{{ field.help_text }}</div>
                                {% endif %}
                            </div>
                            {% endfor %}

                            <div class="text-center">
                                <button type="submit" class="btn btn-get-started btn-lg">Update User</button>
                                <!-- Button to submit the form and update the user -->
                            </div>
                        </form>

                        <div class="mt-3 text-center">
                            <a href="{% url 'agencies:manage_users' %}" class="btn btn-secondary">Back to User
                                Management</a>
                            <!-- Link to navigate back to user management -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

agencies/templates/users/manage_users.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid full-height-bg bg-gray-200">
    <!-- Main container for the manage users section -->
    <div class="container mt-4 full-height-bg bg-gray-200 top-padding">
        <h2 class="roboto text-center">Manage Users</h2>
        <!-- Header for the manage users page -->

        <div class="text-end">
            <a href="{% url 'agencies:add_user' %}" class="btn btn-link project-primary-color" title="Add User">
                <i class="fas fa-plus"></i>
            </a>
            <!-- Button to add a new user -->
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Username</th>
                    <th>Email</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Role</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.get_user_type_display }}</td>
                    <!-- Display user details in table rows -->

                    <td>
                        <a href="{% url 'agencies:edit_user' user.id %}" class="btn btn-green-sm btn-sm me-2">
                            <i class="fas fa-edit"></i> Edit</a>
                        <!-- Button to edit user details -->

                        {% if request.user.user_type == 'admin' %}
                        <a href="{% url 'agencies:delete_user' user.id %}" class="btn btn-outline-danger btn-sm">
                            <i class="fas fa-trash-alt"></i> Delete</a>
                        <!-- Button to delete user, visible only to admin users -->
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6" class="text-center">No users found.</td>
                    <!-- Message displayed when no users are found -->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

agencies/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}

{% block head_title %}Your Profile - TraVault{% endblock %}

{% block content %}
<section id="profile" class="bg-gray-200 full-height-bg">
    <!-- Main container for the user profile section -->
    <div class="container top-padding roboto">
        <div class="row justify-content-center py-5">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Your Profile</h2>
                        <!-- Header for the profile page -->

                        <!-- Display form errors if any -->
                        {% if form.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for field in form %}
                                {% for error in field.errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}

                        <!-- Form to update user profile -->
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }} <!-- Add class to form fields for styling -->
                                {% if field.help_text %}
                                <div class="form-text text-muted">{{ field.help_text }}</div>
                                {% endif %}
                            </div>
                            {% endfor %}

                            <div class="text-center">
                                <button type="submit" class="btn btn-get-started btn-lg">Update Profile</button>
                                <!-- Button to submit the form and update the profile -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

agencies/templates/users/setup_password.html
{% extends "base.html" %}
{% load static %}
{% load custom_tags %}

{% block head_title %}Set Your Password - TraVault{% endblock %}

{% block content %}
<section id="setup-password" class="bg-gray-200 full-height-bg">
    <!-- Main container for the set password section -->
    <div class="container top-padding roboto">
        <div class="row justify-content-center py-5">
            <div class="col-md-6">
                <div class="card shadow">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Set Your Password</h2>
                        <!-- Header for the set password page -->

                        <!-- Display form errors if any -->
                        {% if form.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for field in form %}
                                {% for error in field.errors %}
                                <li>{{ error }}</li>
                                {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                        {% endif %}

                        <!-- Form to set a new password -->
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="mb-3">
                                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                {{ field|add_class:"form-control" }} <!-- Add class to form fields for styling -->
                                {% if field.help_text %}
                                <div class="form-text text-muted">{{ field.help_text }}</div>
                                {% endif %}
                            </div>
                            {% endfor %}

                            <div class="text-center">
                                <button type="submit" class="btn btn-get-started btn-lg">Set Password</button>
                                <!-- Button to submit the form and set the password -->
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}